Window:
  shortcuts:
    focusMapView: 'Ctrl+1'
    focusDocumentView: 'Ctrl+2'
    onlyMapView: 'Ctrl+Shift+1'
    onlyDocumentView: 'Ctrl+Shift+2'
    toggleViews: 'Ctrl+3'
    close: q
    save: s

DocumentView:
  shortcuts: 
    nextPage: 'Ctrl+j'
    previousPage: 'Ctrl+k'
    pageDown: 'Shift+j' 
    pageUp: 'Shift+k'
    pageSmallDown: j 
    pageSmallUp: k
    pageRight: l 
    pageLeft: h 
    update: u
    toggleContinuousMode: c
    fitToPageWidth: w
    fitToPageSize: a
    zoomIn: +
    zoomOut: '-'

BrowserView:
  shortcuts:
    toggleActionsMenu: m
  BrowserMenu:
    toggleNavigation: n

Plugins:

  Fuzzy:
    location: top
    closeOnSelection: True
    shortcuts:
      moveDown: j
      moveUp: k
      onlyPreview: p
      clearEditorFilter: c

  Annotation:
    showAnnotationOverlay: True
    shortcuts:
      open: o
      toggleToggleMenu: 'Shift+t'
      toggleChangeMenu: 'Shift+c'
    colorSystem:
      Main: '#a4de02'
      Definition: '#eefc5e'
      Question: '#c8d9e8'
      Source: '#d3d3d3'

  Bookmarks:
    shortcuts:
      deleteBookmark: d

  Metadata:
    shortcuts:
      changeKind: c
      searchMeta: m
      save: s

  Quickmarks:
    shortcuts:
      delete: d
      setComment: c

  Outline:
    shortcuts:
      expandAll: e
      collapseAll: c
      open: o

  View:
    Cursor:
      height: 10
      tolerance: 0.5


  Anki:
    shortcuts:
      submit: s
      changeDeck: d
      changeModel: f
      clearFields: c
      activateTextSelector: t
      activateImageSelector: i
      addNewDeck: a

  Search:
    shortcuts:
      jumpToNext: n
      jumpToPrevious: p
      showAll: s

  Documents:
    watchFolders:
      - '/home/adam/docs'
    colorSystem:
      book: '#90ee90'
      paper: '#09bb09'
      webpage: '#09aa09'

  Notes:
    baseFolder: '/home/adam/sciebo/doc_notes'
