[tool.poetry]
name = "lura"
version = "0.0.1"
description = "A document viewer"
authors = ["A O <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
# gizmo = {path = "/home/adama/code/gizmo", develop = true}
plug = {path = "/home/adam/code/plug", extras=["qt"], develop = true}

[tool.poetry.scripts]
lura = "lura.main:run"
lurac = "lura.cli:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
