[build-system]

requires=["setuptools"]
build-backend="setuptools.build_meta"

[project]

name="lura"
version='0.0.1'
description='Lura - a document viewer'
dependencies=[
	"gizmo==0.0.1",
	"plug[qplug]==0.0.1",
	"python-poppler-qt5==21.3.0",
	]

[project.scripts]

lura = "lura.main:run"
lurac = "lura.cli:run"

[tools.setuptools.package-data]

"*"=["*"]

[tools.setuptools.packages.find]

where=["src"]
