[Settings]
keywords=['viewer']

[Umay.Settings]
umay_port=19999

[Styler.Settings]
style = 'GreenElf'

[Lookup.Settings]
lookup_port = 43110

[TableView.Settings]
pattern='kind=table;'

[TableView.General]
uid='id'
check_prop='canLocate'
locator_kind='position'

[TableView.Quickmarks]
table_name='Quickmark'
position = {Quickmark = 'dock_right'}
prefix_keys={command = 'q', '|Quickmark' = '<c-.>'}
widget_map={mark = {w = 'Label', p = '0x0x1x1'}}

[TableView.Bookmarks]
table_name='Bookmark'
position = {Bookmark = 'dock_right'}
prefix_keys = {command = 'b', '|Bookmark' = '<c-.>'}
widget_map={id = {w =  'Label', p = '0x0x1x1'},  text = {w = 'TextEdit', p = '1x0x1x1'}}

[TableView.Annotations]
table_name='Annotation'
position = {Annotation = 'dock_right'}
prefix_keys = {command = 'a', '|Annotation' = '<c-.>'}
widget_map={id = {w =  'Label', p = '0x0x1x1'},  text = {w = 'TextEdit', p = '1x0x1x1'}}

[TableView.Metadata]
table_name='Metadata'
position = {Metadata = 'dock_right'}
prefix_keys = {command = 'm', '|Metadata' = '<c-.>'}

[TableView.Metadata.row_map]
title = {w = 'TextEdit'}
author = {w = 'TextEdit'}
year = {w = 'TextEdit'}

[Card.Settings]
prefix_keys = {command = 'c'}

[Card.Keys]
inputField = {key='cu', modes=['normal', 'command']} 

[Picky.Settings]
base = 'https://github.com'
folder = '~/.config/lura/picky'

[[Picky.Picks]]
pick = 'aotabekov91/lura_plugins'
subdir = [
	'src/links',
	'src/visual',
	'src/outline',
	'src/bookmark',
	'src/quickmark',
	# 'src/annotate',
# 	'src/parts',
# 	'src/documents',
	# 'src/annotate_list',
	# 'src/search',
	# 'src/search_list',
	# 'src/autosave',
# 	'src/card',
# 	'src/leaper',
# 	'src/lookup',
# 	'src/pager',
# 	'src/rlist',
	]

[[Picky.Picks]]
pick = 'aotabekov91/ohu'
subdir = [
	'src/ohu/files',
	'src/ohu/pdf_fitz',
	]

[[Picky.Picks]]
pick = 'aotabekov91/plug'
subdir = [
	'src/plug/qt/plugs/runlist',
	# 'src/plug/qt/plugs/move',
	# 'src/plug/qt/plugs/hint',
	# 'src/plug/qt/plugs/resize',
	# 'src/plug/qt/plugs/umay_plug',
	]

[View]
# foldlevel=0
zoomFactor = 0.1
scaleFactor = 1.0
continuousMode = true
layoutMode = 'SinglePage' 
scaleMode = 'FitToWindowWidth' 

[View.Item]
xresol = 72
yresol = 72
rotation = 0
proxyPadding =  0
viewportPadding = 0

[View.Layout]
pageSpacing = 0 

[FitzView]
tileSize =  1024
paperColor = 'gray'
useTiling =  false
trimMargins = false
invertColors = false
decorateLinks = true
decoratePages = false
devicePixelRatio = 1.0
drawMode = 'DefaultMode'
annotationOverlay = true
convertToGrayscale = false
keepObsoletePixmaps = true
copyToClipboardModifiers = 1

[FitzView.Item]
yresol=1

[FitzView.Layout]
pageSpacing = 3 

[ImageView]
continuousMode = false
