[Settings]
keywords=['viewer']

[Umay.Settings]
umay_port=19999

[Styler.Settings]
style = 'GreenElf'

[Lookup.Settings]
lookup_port = 43110

[Card.Settings]
leader_keys = {command = 'c'}

[FileBrowser.Settings]
leader_keys = {command = 'f'}

[Card.Keys]
inputField = {key='cu', modes=['normal', 'command']} 

[FileBrowser.Keys]
toggle = 't'

[FileBrowser.Keys.UI.main.tree]
up = 'k'
down = 'j'

[Picky.Settings]
base = 'https://github.com'
folder = '~/.config/lura/picky'

# [[Picky.Picks]]
# pick = 'aotabekov91/lura_plugins'
# subdir = [
# 	'src/card',
# 	'src/links',
# 	'src/parts',
# 	'src/leaper',
# 	'src/search',
# 	'src/visual',
# 	'src/outline',
# 	'src/autosave',
# 	'src/annotate',
# 	'src/metadata',
# 	'src/bookmark',
# 	'src/documents',
# 	'src/bookmarks',
# 	'src/quickmark',
# 	'src/quickmarks',
# 	'src/annotations',
# 	'src/search_list',
# 	'src/annotate_list',

# 	# 'src/lookup',
# 	# 'src/pager',
# 	# 'src/rlist',
	# ]

[[Picky.Picks]]
pick = 'aotabekov91/plug'
subdir = [
	'src/plug/qt/plugs/run',
	'src/plug/qt/plugs/move',
	'src/plug/qt/plugs/hint',
	'src/plug/qt/plugs/input',
	'src/plug/qt/plugs/resize',
	'src/plug/qt/plugs/styler',
	'src/plug/qt/plugs/command',
	'src/plug/qt/plugs/runlist',
	'src/plug/qt/plugs/powerline',
	'src/plug/qt/plugs/umay_plug',
	'src/plug/qt/plugs/trees/file_tree',
	'src/plug/qt/plugs/styles/green_elf',
	]

[Display.View]
foldlevel=0
zoomFactor = 0.1
scaleFactor = 1.0
continuousMode = true
layoutMode = 'SinglePage' 
scaleMode = 'FitToWindowHeight' 

[Display.View.Item]
xresol = 72
yresol = 72
rotation = 0
proxyPadding =  0
viewportPadding = 0

[Display.View.Layout]
pageSpacing = 0 

[Display.View.PdfView.Item]
yresol=1

[Display.View.PdfView.Layout]
pageSpacing = 3 

[Display.View.PdfView]
tileSize =  1024
paperColor = 'gray'
useTiling =  false
trimMargins = false
invertColors = false
decorateLinks = true
decoratePages = false
devicePixelRatio = 1.0
drawMode = 'DefaultMode'
annotationOverlay = true
convertToGrayscale = false
keepObsoletePixmaps = true
copyToClipboardModifiers = 1

[Display.View.ImageView]
continuousMode = false
