[Settings]

keywords=['viewer', 'document']

[Umay.Settings]

umay_port=19999

[Styler.Settings]

style = 'GreenElf'

[Lookup.Settings]

lookup_port = 43110

[Card.Settings]

prefix_keys = {command = 'c'}

[FileBrowser.Settings]

prefix_keys = {command = 'f'}

[Card.Keys]

inputField = {key='cu', modes=['normal', 'command']} 

[FileBrowser.Keys]

toggle = 't'

[FileBrowser.Keys.UI.main.tree]

up = 'k'
down = 'j'

[Picky.Settings]

base = 'https://github.com'
folder = '~/.config/lura/picky'

[[Picky.Picks]]

pick = 'aotabekov91/lura_plugins'
subdir = [
	'src/modes/search',
	'src/modes/visual',
	'src/annotate',
	'src/annotations',
	'src/annotate_list',
	'src/autosave',
	'src/bookmark',
	'src/bookmarks',
	'src/quickmark',
	'src/quickmarks',
	'src/metadata',
	'src/leaper',
	'src/links',
	'src/documents',
	'src/card',
	'src/parts',
	'src/search_list',
	'src/outline',
# 	# 'src/lookup',
# 	# 'src/pager',
# 	# 'src/rlist',
	]

[[Picky.Picks]]

pick = 'aotabekov91/plug'
subdir = [
	'src/plug/qt/plugs/modes/exec',
	'src/plug/qt/plugs/modes/command', 
	'src/plug/qt/plugs/styles/green_elf',
	'src/plug/qt/plugs/styler',
	'src/plug/qt/plugs/powerline',
	'src/plug/qt/plugs/execlist',
	'src/plug/qt/plugs/trees/file_tree',
	'src/plug/qt/plugs/umay_plug',
	# 'src/plug/qt/modes/move',
	# 'src/plug/qt/modes/hint',
	# 'src/plug/qt/modes/resize',
	# 'src/plug/qt/plugs/handler',
	]

[View]

rotation = 0
zoomFactor = 0.1
pageSpacing = 3 
scaleFactor = 1.0
tileSize =  1024
resolutionX = 72
resolutionY = 72
paperColor = 'gray'
proxyPadding =  0
useTiling =  false
trimMargins = false
viewportPadding = 0
invertColors = false
decorateLinks = true
decoratePages = false
devicePixelRatio = 1.0
continuousView = true
drawMode = 'DefaultMode'
annotationOverlay = true
layoutMode = 'SinglePage' 
convertToGrayscale = false
keepObsoletePixmaps = true
scaleMode = 'FitToPageHeight' 
copyToClipboardModifiers = 1
