Settings:
  port: 20002
  plugs: ~/.config/lura/plugs
  modes: ~/.config/lura/modes

Lookup:
  Settings: 
    lookup_port: 43110

Plugs:
  - aotabekov91/lura_plugins:
      subdir: 
        - tree/main/src/plugs/card
        - tree/main/src/plugs/autosave
        - tree/main/src/plugs/bookmark
        - tree/main/src/plugs/documents
        - tree/main/src/plugs/files
        - tree/main/src/plugs/jumper
        - tree/main/src/plugs/links
        - tree/main/src/plugs/lookup
        - tree/main/src/plugs/metadata
        - tree/main/src/plugs/outline
        - tree/main/src/plugs/pager
        - tree/main/src/plugs/parts
        - tree/main/src/plugs/quickmark
        - tree/main/src/plugs/rlist
        - tree/main/src/plugs/search
        - tree/main/src/plugs/annotate

Modes:
  - aotabekov91/lura_modes:
    - input
    - search
    - normal 

View:
  rotation: 0
  zoomFactor: .1
  pageSpacing: 2
  scaleFactor: 1.
  tileSize:  1024
  resolutionX: 72
  resolutionY: 72
  paperColor: gray
  proxyPadding:  0.
  useTiling:  False
  trimMargins: False
  viewportPadding: 0
  invertColors: False
  decorateLinks: True
  decoratePages: False
  devicePixelRatio: 1.
  continuousView: True
  drawMode: DefaultMode
  annotationOverlay: True
  convertToGrayscale: False
  keepObsoletePixmaps: True
  scaleMode: FitToPageHeight
  copyToClipboardModifiers: 1
  layoutMode: SinglePageLayout
