Settings:
  port: 20002

Card:
  Settings:
    mode_keys:
      command: c
  Keys:
    inputField: 
      key: cu
      modes: 
        - normal
        - command

FileBrowser:
  Settings:
    mode_keys:
      command: f
  Keys:
    toggle: t

Lookup:
  Settings: 
    lookup_port: 43110

Plugman:
  Settings: 
    folder: ~/.config/lura/picky
    base: https://github.com
  Picky:
    - aotabekov91/lura_plugins:
        subdir: 
          - src/plugs/card
          - src/plugs/autosave
          - src/plugs/bookmark
          - src/plugs/documents
          - src/plugs/files
          - src/plugs/jumper
          - src/plugs/links
          - src/plugs/lookup
          - src/plugs/metadata
          - src/plugs/outline
          - src/plugs/pager
          - src/plugs/parts
          - src/plugs/quickmark
          - src/plugs/rlist
          - src/plugs/search
          - src/plugs/annotate
          - src/modes/normal
          - src/modes/visual

    - aotabekov91/plug:
        subdir: 
          - src/plug/qt/modes/exec
          - src/plug/qt/modes/command
          - src/plug/qt/plugs/powerline

View:
  rotation: 0
  zoomFactor: .1
  pageSpacing: 2
  scaleFactor: 1.
  tileSize:  1024
  resolutionX: 72
  resolutionY: 72
  paperColor: gray
  proxyPadding:  0.
  useTiling:  False
  trimMargins: False
  viewportPadding: 0
  invertColors: False
  decorateLinks: True
  decoratePages: False
  devicePixelRatio: 1.
  continuousView: True
  drawMode: DefaultMode
  annotationOverlay: True
  convertToGrayscale: False
  keepObsoletePixmaps: True
  scaleMode: FitToPageHeight
  copyToClipboardModifiers: 1
  layoutMode: SinglePageLayout
