[Settings]
port = 20002

[Plugman.Settings]
base = 'https://github.com'
folder = '~/.config/lura/picky'

[Colorscheme.Settings]

colorscheme = 'default'

[Lookup.Settings]
lookup_port = 43110

[Card.Settings.mode_keys]
command = 'c' 

[FileBrowser.Settings.mode_keys]
command = 'f' 

[Card.Settings.Keys]
inputField = {key='cu', modes=['normal', 'command']} 

[FileBrowser.Settings.Keys]
toggle = 't'

[FileBrowser.Settings.UI.Keys]
# [FileBrowser.Settings.UI.Tree.Keys] Todo
moveUp = 'k'
moveDown = 'j'

[[Plugman.Picky]]

pick = 'aotabekov91/lura_plugins'
subdir = [
	'src/plugs/card',
	'src/plugs/autosave',
	'src/plugs/bookmark',
	'src/plugs/documents',
	'src/plugs/files',
	'src/plugs/jumper',
	'src/plugs/links',
	'src/plugs/lookup',
	'src/plugs/metadata',
	'src/plugs/outline',
	'src/plugs/pager',
	'src/plugs/parts',
	'src/plugs/quickmark',
	'src/plugs/rlist',
	'src/plugs/search',
	'src/plugs/annotate',
	'src/modes/normal',
	'src/modes/visual',
	]

[[Plugman.Picky]]

pick = 'aotabekov91/plug'
subdir = [
	'src/plug/qt/modes/exec',
	# 'src/plug/qt/modes/move',
	# 'src/plug/qt/modes/hint',
	# 'src/plug/qt/modes/resize',
	'src/plug/qt/plugs/styler',
	'src/plug/qt/plugs/execlist',
	'src/plug/qt/plugs/colorscheme',
	'src/plug/qt/modes/command', 
	'src/plug/qt/plugs/powerline',
	]

[View]

rotation = 0
zoomFactor = 0.1
pageSpacing = 2
scaleFactor = 1.0
tileSize =  1024
resolutionX = 72
resolutionY = 72
paperColor = 'gray'
proxyPadding =  0
useTiling =  false
trimMargins = false
viewportPadding = 0
invertColors = false
decorateLinks = true
decoratePages = false
devicePixelRatio = 1.0
continuousView = true
drawMode = 'DefaultMode'
annotationOverlay = true
convertToGrayscale = false
keepObsoletePixmaps = true
scaleMode = 'FitToPageHeight' 
copyToClipboardModifiers = 1
layoutMode = 'SinglePageLayout' 
