[Settings]
keywords=['viewer']

[Umay.Settings]
umay_port=19999

[Styler.Settings]
style = 'GreenElf'

[Lookup.Settings]
lookup_port = 43110

[Card.Settings]
leader_keys = {command = 'c'}

[Card.Keys]
inputField = {key='cu', modes=['normal', 'command']} 

[Picky.Settings]
base = 'https://github.com'
folder = '~/.config/lura/picky'

[[Picky.Picks]]
pick = 'aotabekov91/lura_plugins'
subdir = [
	'src/quickmark',
	'src/quickmarks',
	# 'src/bookmark',
	'src/bookmarks',
	# 'src/links',
	# 'src/metadata',
	# 'src/annotations',
# 	# 'src/search',
# 	# 'src/visual',
# 	# 'src/outline',
# 	# 'src/autosave',
# 	# 'src/annotate',
# 	# 'src/annotate_list',
# # 	'src/card',
# # 	'src/parts',
# # 	'src/leaper',
# # 	'src/documents',
# # 	'src/search_list',
# # 	'src/lookup',
# # 	'src/pager',
# # 	'src/rlist',
	]

[[Picky.Picks]]
pick = 'aotabekov91/ohu'
subdir = [
	'src/ohu/files'
	]

[[Picky.Picks]]
pick = 'aotabekov91/plug'
subdir = [
	'src/plug/qt/plugs/run',
	'src/plug/qt/plugs/styler',
	'src/plug/qt/plugs/runlist',
	'src/plug/qt/plugs/command',
	'src/plug/qt/plugs/powerline',
	'src/plug/qt/plugs/styles/green_elf',
	# 'src/plug/qt/plugs/move',
	# 'src/plug/qt/plugs/hint',
	# 'src/plug/qt/plugs/input',
	# 'src/plug/qt/plugs/resize',
	# 'src/plug/qt/plugs/umay_plug',
	]

[View]
foldlevel=0
zoomFactor = 0.1
scaleFactor = 1.0
continuousMode = true
layoutMode = 'SinglePage' 
scaleMode = 'FitToWindowWidth' 

[View.Item]
xresol = 72
yresol = 72
rotation = 0
proxyPadding =  0
viewportPadding = 0

[View.Layout]
pageSpacing = 0 

[FitzView]
tileSize =  1024
paperColor = 'gray'
useTiling =  false
trimMargins = false
invertColors = false
decorateLinks = true
decoratePages = false
devicePixelRatio = 1.0
drawMode = 'DefaultMode'
annotationOverlay = true
convertToGrayscale = false
keepObsoletePixmaps = true
copyToClipboardModifiers = 1

[FitzView.Item]
yresol=1

[FitzView.Layout]
pageSpacing = 3 

[ImageView]
continuousMode = false
