[Settings]
handler_port = 20002

[Plugman.Settings]
base = 'https://github.com'
folder = '~/.config/lura/picky'

[Styler.Settings]
style = 'GreenElf'

[Lookup.Settings]
lookup_port = 43110

[Card.Settings.mode_keys]
command = 'c' 

[FileBrowser.Settings.mode_keys]
command = 'f' 

[Card.Settings.Keys]
inputField = {key='cu', modes=['normal', 'command']} 

[FileBrowser.Settings.Keys]
toggle = 't'

[FileBrowser.Settings.UI.Keys]
# [FileBrowser.Settings.UI.Tree.Keys] Todo
moveUp = 'k'
moveDown = 'j'

[[Plugman.Picky]]
pick = 'aotabekov91/lura_plugins'
subdir = [
	'src/modes/normal',
	'src/modes/visual',
	'src/annotate',
	'src/annotations',
	'src/annotate_list',
	'src/autosave',
	'src/bookmark',
	'src/bookmarks',
	'src/quickmark',
	'src/quickmarks',
	'src/metadata',
	'src/outline',
	'src/leaper',
	# 'src/card',
	# 'src/modes/search',
# 	# 'src/documents',
# 	# 'src/links',
# 	# 'src/lookup',
# 	# 'src/pager',
# 	# 'src/parts',
# 	# 'src/rlist',
	]

[[Plugman.Picky]]
pick = 'aotabekov91/plug'
subdir = [
	'src/plug/qt/plugs/modes/exec',
	'src/plug/qt/plugs/modes/command', 
	'src/plug/qt/plugs/styles/green_elf',
	'src/plug/qt/plugs/styler',
	'src/plug/qt/plugs/powerline',
	'src/plug/qt/plugs/execlist',
	'src/plug/qt/plugs/trees/file_tree',
	# 'src/plug/qt/modes/move',
	# 'src/plug/qt/modes/hint',
	# 'src/plug/qt/modes/resize',
	# 'src/plug/qt/plugs/umay',
	# 'src/plug/qt/plugs/handler',
	]

[View]
rotation = 0
zoomFactor = 0.1
pageSpacing = 3 
scaleFactor = 1.0
tileSize =  1024
resolutionX = 72
resolutionY = 72
paperColor = 'gray'
proxyPadding =  0
useTiling =  false
trimMargins = false
viewportPadding = 0
invertColors = false
decorateLinks = true
decoratePages = false
devicePixelRatio = 1.0
continuousView = true
drawMode = 'DefaultMode'
annotationOverlay = true
convertToGrayscale = false
keepObsoletePixmaps = true
scaleMode = 'FitToPageHeight' 
copyToClipboardModifiers = 1
layoutMode = 'SinglePageLayout' 
