Plugs:
  - aotabekov91/lura_plugins:
    - annotate
    - card
Modes:
  - aotabekov91/lura_modes:
    - input
    - search
    - normal 
Settings:
  port: 20002
  plugs_folder: /tmp
  modes_folder: /tmp
View:
  rotation: 0
  zoomFactor: .1
  pageSpacing: 2
  scaleFactor: 1.
  tileSize:  1024
  resolutionX: 72
  resolutionY: 72
  paperColor: gray
  proxyPadding:  0.
  useTiling:  False
  trimMargins: False
  viewportPadding: 0
  invertColors: False
  decorateLinks: True
  decoratePages: False
  devicePixelRatio: 1.
  continuousView: True
  drawMode: DefaultMode
  annotationOverlay: True
  convertToGrayscale: False
  keepObsoletePixmaps: True
  scaleMode: FitToPageHeight
  copyToClipboardModifiers: 1
  layoutMode: SinglePageLayout
